name: users
dependencies:
  - python=3.6
  - pip
  - pip:
      - pytest==4.*
      - flake8==3.*
      - pylint==2.*
      - kubernetes==9.*
      - google-api-python-client==1.*
      - google-cloud-storage==1.*
      - PyMySQL==0.9.*
      - shortuuid==0.5.*
