apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch2
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: batch2
  labels:
    app: batch2
spec:
  selector:
    matchLabels:
      app: batch2
  replicas: 1
  template:
    metadata:
      labels:
        app: batch2
    spec:
      serviceAccountName: batch2
      containers:
      - name: batch2
        image: "gcr.io/hail-vdc/batch2:latest"
        resources:
          requests:
            memory: "250M"
            cpu: "0.5"
        env:
        ports:
         - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      tolerations:
      - key: "preemptible"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: batch2
  labels:
    app: batch2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: batch2
