---
repos:
  - repo: local
    hooks:
      - id: check-ci
        name: check-ci
        entry: bash pre-commit-make-shim ci
        files: ci/
        language: system
        types: [python]
        require_serial: true
      - id: check-batch
        name: check-batch
        entry: bash pre-commit-make-shim batch
        files: batch/
        language: system
        types: [python]
        require_serial: true
      - id: check-auth
        name: check-auth
        entry: bash pre-commit-make-shim auth
        files: auth/
        language: system
        types: [python]
        require_serial: true
      - id: check-web_common
        name: check-web_common
        entry: bash pre-commit-make-shim web_common
        files: web_common/
        language: system
        types: [python]
        require_serial: true
      - id: check-gear
        name: check-gear
        entry: bash pre-commit-make-shim gear
        files: gear/
        language: system
        types: [python]
        require_serial: true
      - id: check-hailtop
        name: check-hailtop
        entry: bash pre-commit-make-shim hailtop
        files: hail/python/hailtop
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        types: [file] # By default only runs on .jinja files, this disables that
        files: \.html$
