apiVersion: v1
kind: Service
metadata:
  name: site
  labels:
    app: site
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: site
---
apiVersion: v1
kind: Service
metadata:
  name: scorecard
  labels:
    app: scorecard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: scorecard
---
apiVersion: v1
kind: Service
metadata:
  name: hail-ci
  labels:
    app: hail-ci
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: hail-ci
---
apiVersion: v1
kind: Service
metadata:
  name: ci2
  labels:
    app: ci2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ci2
---
apiVersion: v1
kind: Service
metadata:
  name: upload
  labels:
    app: upload
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: upload
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: notebook
---
apiVersion: v1
kind: Service
metadata:
  name: notebook2
  labels:
    app: notebook2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: notebook2
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: router-deployment
  labels:
    app: router
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: router
  replicas: 1
  template:
    metadata:
      labels:
        app: router
        hail.is/sha: "{{ code.sha }}"
    spec:
      containers:
       - name: router
         image: {{ router_image.image }}
         env:
          - name: DOMAIN
            value: {{ default_ns.domain }}
         ports:
          - containerPort: 80
         readinessProbe:
           httpGet:
             path: /healthcheck
             port: 80
           initialDelaySeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: router
