name: hail
dependencies:
- python=3.6
- Sphinx=1.8.3
- sphinxcontrib=1.0
- conda-forge::nbsphinx=0.3.1
- conda-forge::sphinx_rtd_theme=0.4.2
- numpy=1.14.0
- pandas=0.23.4
- matplotlib=2.2.3
- seaborn=0.8.1
- bokeh=0.12.13
- jupyter=1.0.0
- pip=10.0.1
- pytest=3.8.0
- pytest-html=1.19
- flask=0.12.2
- pip:
    - parsimonious==0.8.0
    - ipykernel==4.9.0
    - pytest-xdist==1.22.2
    - decorator==4.3.0
    - pyspark==2.4.0
