name: hail-py3.7
dependencies:
- python=3.7
- Sphinx=1.8.3
- sphinxcontrib=1.0
- conda-forge::nbsphinx=0.3.5
- conda-forge::sphinx_rtd_theme=0.4.2
- numpy=1.15.3
- pandas=0.23.4
- matplotlib=3.0.1
- seaborn=0.9.0
- bokeh=1.0.0
- jupyter=1.0.0
- pip=18.0
- pytest=3.9.2
- pytest-html=1.19
- flask=0.12.2
- pip:
    - parsimonious==0.8.1
    - ipykernel==5.1.0
    - pytest-xdist==1.23.2
    - decorator==4.3.0
    - pyspark==2.4.0
