name: hail
dependencies:
- python=3.6
- numpy=1.14.0
- pandas=0.23.0
- matplotlib=2.2.3
- seaborn=0.8.1
- bokeh=0.12.13
- jupyter=1.0.0
- pip=10.0.1
- pip:
    - parsimonious==0.8.0
    - ipykernel==4.9.0
    - decorator==4.3.0
    - gcsfs==0.2.1
    - hurry.filesize==0.9
